title: My blog
email: chrismetheridge@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "chrisetheridge.github.io" 
markdown: kramdown
theme: fundamental
plugins:
  - jekyll-feed