title: chrisetheridge's blog
author:
  name: Chris Etheridge
  github: chrisetheridge
  twitter: chrisetheridge

favicon: false

footer:
  separator: '|'
  content: Ⓒ chris etheridge
  year: true

baseurl: ""
url: "https://chrisetheridge.github.io"

description: TODO

# build
markdown: kramdown
theme: fundamental


# theme configuration
enabled:
  breadcrumbs: true
  tags: true
  comments: false
  rss: false
  seo: true
  social:
    enabled: true
    twitter: true
    facebook: true
    messenger: false
    whatsapp: false

# disqus sharing/comments
disqus_shortname: your-forum-shortname

# social sharing colors
socialBtnsColor: '#4845DF'

# installed plugins
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate

# compress sass
sass:
  style: compressed

# frontend defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      author: "YOUR NAME"
      comments: true


permalink: pretty

# plugin configuration
# archive plugin
jekyll-archives:
  enabled:
  - year
  - month
  - tags
  layout: 'archive'
  layouts:
    tag: 'tag_page'
    month: month
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

paginate: 20